### ISSUE TITLE
While running db2tppg.pl getting an error

### ISSUE THREAD

**Issue by dibyendub** [dalibo/db2topg#2]
Getting the following error:-

technology@technology-EPS:~/Downloads/db2topg-master$ ./db2topg.pl -f /home/technology/Downloads/bqeps_l.sql -o db_migration -d bqeps_l -u db2admin -p admin@123
I don't understand <CREATE SEQUENCE "EPS"."ACTION_TYPE_MAIL_MASTER" AS INTEGER  START WITH 100 INCREMENT BY 1 MINVALUE 100 MAXVALUE 2147483647 NO CYCLE NO CACHE ORDER> at ./db2topg.pl line 934, <IN> line 3.

Please suggest.

**Comment by marco44** [comment]
Well, this should work, as far as I see from the code. Can you send me the dump to cousinmarc at gmail dot com ? (I won't publish the dump, of course)

**Comment by dibyendub** [comment]
Thanks Marco for your reply.

Please find attached the sql dump.

**Comment by marco44** [comment]
I don't see any attachment.

**Comment by dibyendub** [comment]
Sorry for the inconvenience. But it was there. I am zipping the sql file.
Please find the zip file for your reference.

Please let me know if you get it or not?

Thanks,
Dibyendu

**Comment by marco44** [comment]
No. Please don't respond to github emails, and send me the attached document directly at cousinmarc at gmail dot com

**Comment by marco44** [comment]
Ok, very weird…

All DB2's dumps I had untill now had multiline create sequences. Not this one. What version of DB2 is it ? Is it UDB or DB2 for zOS ?

**Comment by marco44** [comment]
Solved
