### ISSUE TITLE
Error while executing db2topg.pl file

### ISSUE THREAD

**Issue by praveenjayaraj** [dalibo/db2topg#4]
Hi,

When I execute the db2topg.pl file for converting my DB2 DDL to PostgreSQL DB, I am getting the following error.

./db2topg.pl
./db2topg.pl: line 7: syntax error near unexpected token `newline'
./db2topg.pl: line 7: `<!DOCTYPE html>'

Also when I tried an alternate way I got this,

perl db2topg.pl  -f ddl.query -o test -d inach -u achinst1 -p Achuat@db
Bareword found where operator expected at db2topg.pl line 23, near "<title>db2topg"
        (Missing operator before db2topg?)
syntax error at db2topg.pl line 10, near "<"
Unrecognized character \xC2 in column 39 at db2topg.pl line 23.

Help me out.

**Comment by marco44** [comment]
Well, there errors are very weird.

You get errors in the comments (line 7 and 10) and in an empty line (23)

Please tell me more: what operating system, how did you get db2topg, what did you do until now ?

**Comment by praveenjayaraj** [comment]
I am running this on a RHEL 6.8 host. 
I just downloaded the db2topg from github and in the first step I am facing issues.

**Comment by marco44** [comment]
Can you check the content of your db2topg.pl file? Is it a perl script ? Your error looks like the content of this file isn't what is expected
