### ISSUE TITLE
Issue while using db2topg.pl

### ISSUE THREAD

**Issue by sarathmv** [dalibo/db2topg#6]
ADMIN.MSTJCNODELOCKPI is clustered.Clustered (or IOT) indexes aren't supported in PostgreSQL. Creating a normal index
I don't understand <create function db2ext.textSearch ( pTextSearchArg VARCHAR(4096), pIndexCreator> at ./db2topg.pl line 1084, <IN> line 17824.

**Comment by marco44** [comment]
Ok, the first message is normal: there are no clustered indexes in postgresql (a clustered index in db2 is when the index is the table), so in postgresql, we create a normal index, and print a warning.

It's the second line that is the error. There is something the script doesn't understand in it. If you want, you can send me the dump to cousinmarc at gmail dot com, I'll give it a look.
